# Site settings
title:       [PRAM BAHARSYAH]
email:       mbaharsyah@gmail.com
author:      Pram Baharsyah
description: "Notes About Anything"
baseurl:     ""
url:         "http://mbaharsyah.xyz"
date_format: "%b %-d, %Y"

# Google services
google_analytics:
google_verification:

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  false
show_social_icons:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: mbaharsyah

# Social icons
github_username: mbaharsyah
bitbucket_username:
stackoverflow_id: kimikanen
twitter_username: kimikanen
google_plus_id:
linkedin_username: mbaharsyah
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
